# Generated by Django 4.1.2 on 2022-11-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookadd",
            fields=[
                ("Book_Name", models.CharField(max_length=122)),
                ("Author_Name", models.CharField(max_length=122)),
                ("Price", models.IntegerField()),
                ("Copies", models.IntegerField(default=1)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
