# Generated by Django 4.1.2 on 2022-11-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_management", "0002_memberadd"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookadd", old_name="id", new_name="Book_id",
        ),
    ]
