# Generated by Django 4.1.2 on 2022-11-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_management", "0003_rename_id_bookadd_book_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memberadd", old_name="id", new_name="Member_id",
        ),
    ]
