# Generated by Django 4.1.2 on 2022-11-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_management", "0006_returnbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookadd",
            name="Remaining_Copies",
            field=models.IntegerField(null=True),
        ),
    ]
