# Generated by Django 4.1.2 on 2022-11-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_management", "0007_bookadd_remaining_copies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issuebook", old_name="Book_id", new_name="Book",
        ),
        migrations.RenameField(
            model_name="issuebook", old_name="Member_id", new_name="Member",
        ),
        migrations.RenameField(
            model_name="returnbook", old_name="Book_id", new_name="Book",
        ),
        migrations.RenameField(
            model_name="returnbook", old_name="Member_id", new_name="Member",
        ),
    ]
